---
title: "expandVar"
author: "JHD"
date: "03/06/2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{expandVar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(epiuf)


```

## Expand function

To expand a variable containing more than one value into new individual variables with Y/N values
The list of expected values must be passed as parameters together with the name of the new variable to be created 
The format of the list is :
```{r eval=FALSE}
    list("value1"="variable_name1",    
         "value2"="variable_name2"    
       )    
```


Example :
```{r data}
testvac <- data.frame(Id = 1:3 , 
                      Vaccs = c("1|2|3", "2", "3|1"))


InfoSource <- list("1" = "vacccard",
                   "2" = "registry",
                   "3" = "hospnotes",
                   "9" = "oth") 

  df <- expandVar(data = testvac, varname =Vaccs, valueslist= InfoSource) 
head(df)


```

## Another example with label comma separated


```{r usage }


data <- data.frame(Id = 1:4 , 
                   Vaccs = c("pfizer,moderna"," ", "pfizer", "moderna"))
brand <- list("pfizer"="PFIZER",
              "moderna"="MODERNA"
              )

data <-  expandVar(data,Vaccs,brand)

head(data)
```


```{r usingdico }


data <- data.frame(Id = 1:4 , 
                   Vaccs = c("pfizer,moderna"," ", "pfizer", "moderna"))
file1 <- externalFile("genericdictionary.xlsx")
openDictionary(file1)
data <- expandVarAll(data)

head(data)
```




