---
title: "findAndReplace"
author: "epi-gde"
date: "2023-10-20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{findAndReplace}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(epiuf)
file1 <- "temp_text1.R"
file2 <- "temp_text2.R"
file3 <- "temp_text3.R"

```



```{r charCount}
  charCount("c","cancan")
  charCount("essai"," this is an essai" )
  charCount("c","ccc" )
  charCount("ce",c("cacec","ceci" ))
  df <- data.frame(c("cacececi","ceci" ,"non","ace"))
  charCount("ce",df)
  charCount("\\bce\\b",df)
  df <- data.frame(c("ca cece ci","ce ci" ,"non","a ce"))
  charCount("\\bce\\b",df)
  df <- data.frame(c("ca cece ci","ce ci" ,"non","a ce"),c("ca cececi","ce ci" ,"non","ace"))
  charCount("\\bce\\b",df)
  charCount("","essai")
  charCount("e","")
  charCount("\\.","21.15.98")
  
  
```




```{r prepFiles, echo=FALSE}
lines <- c(
"# test script for findAndReplace",
"# word to be replaced : oldword",
"#  old_word",
"#  oldword --  oldword)")

writeLines(lines, file1)
writeLines(lines, file2)
writeLines(lines, file3)
```

**listFiles** is a simplified version of list.files which accept jokers (fullpath is automaticaly set with recursive flag)

```{r listFiles}
listFiles(pattern="temp_*.R")
listFiles("R","c*")
```

**filesFindReplace** is a generic function to make batch replacement You can call this function for one file, a list of files, a directory, a pattern to filter files or any combination of previous option.

```{r replaceinFiles}
  filesFindReplace(c(file1,file2),pattern="oldword",replacement = "newword",listonly=TRUE)

  filesFindReplace(file3,pattern=c("oldword","old_word"),replacement = "newword",listonly=TRUE)
 
  filesFindReplace(file1,pattern="oldword",replacement = "newword")
  cat(readLines(file1),sep="\n")
  
  file4 <- externalFile("testrename.xlsx")
  filesFindReplace(file4,"patient","subject",word=TRUE, ignore.case = TRUE, listonly=TRUE)
  filesFindReplace(file4,"patient","subject",word=TRUE, ignore.case = TRUE)
  
 
```

```{r cleaning, echo=FALSE }
if(file.exists(file1)) r <- file.remove(file1)
if(file.exists(file2)) r <- file.remove(file2)
if(file.exists(file3)) r <- file.remove(file3)

```
